services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      LOGGING_FILE: /fluentd/log/app.log # Set the log output location
    depends_on:
      - fluentd
    volumes:
      - app_logs:/fluentd/log

  fluentd:
    image: fluent/fluentd:v1.14-1
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - app_logs:/fluentd/log

volumes:
  app_logs:
